server:
  port: 8090
spring:
  application:
    name: crewmeister
  datasource:
    username: root
    password: 0C2D4B0F3604
    url: jdbc:mysql://13.235.134.155:3300/crewmeister
    driver-class-name: com.mysql.cj.jdbc.Driver
  #flyway:
  #  url: ${SPRING_DATASOURCE_WRITER_URL:jdbc:mysql://localhost:3306/challenge?createDatabaseIfNotExist=true}
  #  user: ${SPRING_DATASOURCE_USERNAME:root}
  #  password: ${SPRING_DATASOURCE_PASSWORD:dev}
  #  enabled: true


management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,prometheus}